CREATE TABLE ADDRESS (
    ADDRESS_ID int NOT NULL AUTO_INCREMENT,
    STREET_1 varchar(255),
    STREET_2 varchar(255),
    CITY varchar(255),
    STATE varchar(255),
    ZIP_CODE 	varchar(255),
    PRIMARY KEY(ADDRESS_ID)
);

CREATE TABLE USERS (
    USERS_ID int NOT NULL AUTO_INCREMENT,
    LOGON_ID varchar(255),
    PASSWORD varchar(255),
    ADDRESS_ID int,
    FOREIGN KEY(ADDRESS_ID)
    REFERENCES ADDRESS(ADDRESS_ID),
    PRIMARY KEY(USERS_ID)
);

CREATE TABLE USERDESC (
    USERS_ID int,
    BIRTHDAY DATE,
    PHONE varchar(255),
    CELL_PHONE varchar(255),
    TIME_ZONE varchar(255),
    PROFILE_IMAGE longblob,
    FOREIGN KEY(USERS_ID)
    REFERENCES USERS(USERS_ID)
);

CREATE TABLE WORKHISTORY (
    WORKHISTORY_ID int NOT NULL AUTO_INCREMENT,
    USERS_ID int,
    JOB_TITLE varchar(255),
    COMPANY_NAME varchar(255),
    YEARS_OF_SERVICE int,
    FOREIGN KEY(USERS_ID)
    REFERENCES USERS(USERS_ID),
    PRIMARY KEY(WORKHISTORY_ID)
);


CREATE TABLE EDUCATIONHISTORY(
    EDUCATIONHISTORY_ID int NOT NULL AUTO_INCREMENT,
    USERS_ID int,
    DEGREE_TYPE varchar(255),
    DEGREE_DISCIPLINE varchar(255),
    YEARS_ACHEIVED int,
    FOREIGN KEY(USERS_ID)
    REFERENCES USERS(USERS_ID),
    PRIMARY KEY(EDUCATIONHISTORY_ID)
);

